import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AuthContextProvider } from "@/app/(routes)/auth/_auth-contexts/auth-context";
import { ProgressBar, ProgressBarProvider } from "react-transition-progress";
import { Toaster } from "react-hot-toast";
import { Navbar } from "@/app/components/navbar";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProgressBarProvider>
          {/* Keep the z-index of  ProgressBar high enough to show it above all elements*/}
          <ProgressBar className="fixed h-1 shadow-lg shadow-sky-500/20 bg-blue-600 top-0 z-10" />
          <AuthContextProvider>
           <Navbar />
            <main className="max-w-7xl m-auto">
               
              
              {children}</main>
          </AuthContextProvider>
        </ProgressBarProvider>
        <Toaster />
      </body>
    </html>
  );
}
